title: Maheshwar Hiremath
description: Software Engineer — Java • Spring Boot • AWS • Microservices • Python
# Simple, official Pages theme (easy + zero build headaches)
remote_theme: mistakes/minimal-mistakes@4.26.2
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Site URL (update with your username)
url: https://mghiremath.github.io

# Navigation (shows on theme header)
nav:
  - title: Projects
    url: /#projects
  - title: About
    url: /#about
  - title: Contact
    url: /#contact
