title: Maheshwar Hiremath
description: Software Engineer — Java • Spring Boot • AWS • Microservices • Python • Deep Neural Nets
url: https://mg.hiremath.github.io

remote_theme: mmistakes/minimal-mistakes@4.26.2
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-include-cache

# Minimal Mistakes settings
minimal_mistakes_skin: "dark"  # try: "mint", "default", "contrast", "plum"
logo: /assets/img/avatar.jpg  # optional

author:
  name: "Maheshwar Hiremath"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mghiremath"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:mg.hiremath1996@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/"

# Enable pretty permalinks
permalink: /:categories/:title/

# Navigation (header)
navigation:
  - title: "Projects"
    url: /#projects
  - title: "About"
    url: /#about
  - title: "Contact"
    url: /#contact

# Include our custom CSS
include:
  - _pages
  - assets/css/custom.css
